apiVersion: v2
name: moco
description: MySQL operator on Kubernetes using GTID-based semi-synchronous replication.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.5.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: 0.15.0

# This version does not necessarily match the supported version. This version number
# will be updated when there is an obviously uninstallable version. If there are no
# problems, update only moco/README.md#supported-software for the corresponding kubernetes version.
kubeVersion: ">= 1.22.0"
