version: 2.1

commands:
  e2e-command:
    description: "e2e test"
    steps:
      - run:
          name: Update PATH and Define Environment Variable at Runtime
          command: |
            echo 'export GOPATH=/home/circleci/go' >> $BASH_ENV
            echo 'export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: setup golang
          command: |
            sudo rm -rf /usr/local/go
            GO_VERSION=1.13.4
            curl -fsL https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz | sudo tar xzf - -C /usr/local
      - run:
          name: Setup
          command: |
            make setup
            cd e2e
            make setup
      - run:
          name: Run test
          command: |
            cd e2e
            make launch-kind test

jobs:
  build:
    docker:
      - image: quay.io/cybozu/golang:1.13-bionic
    working_directory: /work
    steps:
      - checkout
      - run: make setup SUDO=""
      - run:
          name: Confirm manifests and api code were generated
          command: |
            make manifests generate
            diffs=$(git diff --name-only)
            if [ "$diffs" != "" ]; then printf "%s\n" "$diffs"; exit 1; fi
      - run: make test
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build/moco-controller
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build/entrypoint
      - persist_to_workspace:
          root: build
          paths: ["*"]
  image:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: cp -a /tmp/workspace build
      - setup_remote_docker
      - run: docker build . -t quay.io/cybozu/moco:latest
      - run:
          name: Push docker image to Quay.io
          command: |
            if [ "$CIRCLE_TAG" = "" ]; then exit 0; fi
            docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
            echo "pushing image ..."
            TAG=$(echo $CIRCLE_TAG | cut -c 2-)
            docker tag quay.io/cybozu/moco:latest quay.io/cybozu/moco:$TAG
            docker push quay.io/cybozu/moco:$TAG
            if echo $TAG | grep -q -e - ; then
                echo ===== Skip pushing branch tags for pre-release $TAG =====
                exit 0
            fi
            BRANCH=$(echo $TAG | cut -d "." -f 1-2)
            docker tag quay.io/cybozu/moco:latest quay.io/cybozu/moco:$BRANCH
            docker push quay.io/cybozu/moco:$BRANCH
  e2e:
    machine:
      image: ubuntu-1604:201903-01
    resource_class: large
    working_directory: /home/circleci/work
    steps:
      - checkout
      - e2e-command
  publish-github-release:
    docker:
      - image: quay.io/cybozu/golang:1.13-bionic
    steps:
      - attach_workspace:
          at: ./artifacts
      - run: ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_TAG} ./artifacts/entrypoint

workflows:
  version: 2
  main:
    jobs:
      - build
      - image:
          requires:
            - build
            - e2e
      - e2e
  release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - image:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
