resources:
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- mysqlcluster_editor_role.yaml
- mysqlcluster_viewer_role.yaml
- backuppolicy_editor_role.yaml
- backuppolicy_viewer_role.yaml
