apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../config
images:
  - name: ghcr.io/cybozu-go/moco
    newName: controller
    newTag: dev
# Use the below patch if you want try an local build moco-agent image
patchesStrategicMerge:
  - patch.yaml 
