apiVersion: apps/v1
kind: Deployment
metadata:
  name: moco-controller-manager
  namespace: moco-system
spec:
  template:
    spec:
      containers:
      - name: manager
        imagePullPolicy: Never
        args:
          - --binary-copy-container-image=moco-agent:dev
