apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- name: statefulset.kb.io
  objectSelector:
    matchLabels:
      app.kubernetes.io/created-by: moco
