apiVersion: moco.cybozu.com/v1alpha1
kind: MySQLCluster
metadata:
  name: mysqlcluster
spec:
  replicas: 3
  replicationSourceSecretName: replication-source-secret
  podTemplate:
    spec:
      containers:
      - name: mysqld
        image: mysql:dev
        ports:
        - containerPort: 3306
          protocol: TCP
        resources:
          requests:
            memory: "512Mi"
        livenessProbe:
          exec:
            command: ["/moco-bin/moco-agent", "ping"]
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 10
          periodSeconds: 5
      - name: err-log
        image: fluent/fluent-bit:1.7.2
        volumeMounts:
        - name: err-fluent-bit-config
          mountPath: /fluent-bit/etc/fluent-bit.conf
          readOnly: true
          subPath: fluent-bit.conf
        - name: var-log
          mountPath: /var/log/mysql
          readOnly: true
      - name: slow-log
        image: fluent/fluent-bit:1.7.2
        volumeMounts:
        - name: slow-fluent-bit-config
          mountPath: /fluent-bit/etc/fluent-bit.conf
          readOnly: true
          subPath: fluent-bit.conf
        - name: var-log
          mountPath: /var/log/mysql
          readOnly: true
      securityContext:
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
      volumes:
        - name: err-fluent-bit-config
          configMap:
            name: err-fluent-bit-config
        - name: slow-fluent-bit-config
          configMap:
            name: slow-fluent-bit-config
  dataVolumeClaimTemplateSpec:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 1Gi
  mysqlConfigMapName: mycnf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mycnf
data:
  max_connections: "5000"
  max_connect_errors: "10"
  max_allowed_packet: 1G
  max_heap_table_size: 64M
  pid_file: /hoge/fuga
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: err-fluent-bit-config
data:
  fluent-bit.conf: |-
    [INPUT]
      Name           tail
      Path           /var/log/mysql/mysql.err
      Read_from_Head true
    [OUTPUT]
      Name     file
      Match    *
      Path     /dev
      File     stdout
      Format   template
      Template {log}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slow-fluent-bit-config
data:
  fluent-bit.conf: |-
    [INPUT]
      Name           tail
      Path           /var/log/mysql/mysql.slow
      Read_from_Head true
    [OUTPUT]
      Name     file
      Match    *
      Path     /dev
      File     stdout
      Format   template
      Template {log}
